<a href="https://colab.research.google.com/github/lavjachica/programacionpython-2024/blob/main/Ejercicioparcial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [84]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [85]:
ruta = "/content/drive/My Drive/ejercicioprogramacion/datanueva.csv"

In [86]:
datos = pd.read_csv(ruta)
datos.head(5)
datos.describe()  ### resumen estadistico condensado

                ID  IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  1000.000000  843.000000  1.000000e+03
mean    500.500000     7.949300   77.971530  2.736929e+05
std     288.819436     0.275491   12.376099  3.273727e+05
min       1.000000     7.600000   28.000000  2.508800e+04
25%     250.750000     7.700000   70.000000  5.552625e+04
50%     500.500000     7.900000   79.000000  1.385485e+05
75%     750.250000     8.100000   87.000000  3.741612e+05
max    1000.000000     9.300000  100.000000  2.343110e+06

In [87]:
datos = pd.read_csv(ruta)
datos.head()

,Series_Title,ID,Poster_Link,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1,https://m.media-amazon.com/images/M/MV5BMDFkYT...,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,2,https://m.media-amazon.com/images/M/MV5BM2MyNj...,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,3,https://m.media-amazon.com/images/M/MV5BMTMxNT...,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,4,https://m.media-amazon.com/images/M/MV5BMWMwMG...,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,5,https://m.media-amazon.com/images/M/MV5BMWU4N2...,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [88]:
print(f'Cantidad de filas y columnas del data set: {datos.shape}') ##dimension del dataset

Cantidad de filas y columnas del data set: (1000, 17)

In [89]:
datos.info() ###muestra la cantidad de filas, registro, muestra el tipo de estructura de dato de cada columna, por ej. int64 es un dato numerico

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   ID             1000 non-null   int64
 2   Poster_Link    1000 non-null   object
 3   Released_Year  1000 non-null   object
 4   Certificate    899 non-null    object
 5   Runtime        1000 non-null   object
 6   Genre          1000 non-null   object
 7   IMDB_Rating    1000 non-null   float64
 8   Overview       1000 non-null   object
 9   Meta_score     843 non-null    float64
 10  Director       1000 non-null   object
 11  Star1          1000 non-null   object
 12  Star2          1000 non-null   object
 13  Star3          1000 non-null   object
 14  Star4          1000 non-null   object
 15  No_of_Votes    1000 non-null   int64
 16  Gross          831 non-null    object
dtypes: float64(2), int64(2), object(13)
memory usage: 132.9+ KB

In [90]:
datos.isnull() ### identifica valores nulos/vacios

,Series_Title,ID,Poster_Link,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
999,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

In [91]:
datos.isnull().any()   ### En los True existen valores vacios CONSULTA LAS COLUMNAS CON VACIOS

Series_Title     False
ID               False
Poster_Link      False
Released_Year    False
Certificate       True
Runtime          False
Genre            False
IMDB_Rating      False
Overview         False
Meta_score        True
Director         False
Star1            False
Star2            False
Star3            False
Star4            False
No_of_Votes      False
Gross             True
dtype: bool

In [92]:
filas_nulas = datos[datos.isnull().any(axis=1)]
filas_nulas

,Series_Title,ID,Poster_Link,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
18,Hamilton,19,https://m.media-amazon.com/images/M/MV5BNjViNW...,2020,PG-13,160 min,"Biography, Drama, History",8.6,The real life of one of America's foremost fou...,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
20,Soorarai Pottru,21,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,2020,U,153 min,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
30,Seppuku,31,https://m.media-amazon.com/images/M/MV5BYjBmYT...,1962,NaN,133 min,"Action, Drama, Mystery",8.6,When a ronin requesting seppuku at a feudal lo...,85.0,Masaki Kobayashi,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,42004,NaN
32,It's a Wonderful Life,33,https://m.media-amazon.com/images/M/MV5BZjc4ND...,1946,PG,130 min,"Drama, Family, Fantasy",8.6,An angel is sent from Heaven to help a despera...,89.0,Frank Capra,James Stewart,Donna Reed,Lionel Barrymore,Thomas Mitchell,405801,NaN
46,Hotaru no haka,47,https://m.media-amazon.com/images/M/MV5BZmY2Nj...,1988,U,89 min,"Animation, Drama, War",8.5,A young boy and his little sister struggle to ...,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,Blowup,994,https://m.media-amazon.com/images/M/MV5BYTE4YW...,1966,A,111 min,"Drama, Mystery, Thriller",7.6,A fashion photographer unknowingly captures a ...,82.0,Michelangelo Antonioni,David Hemmings,Vanessa Redgrave,Sarah Miles,John Castle,56513,NaN
995,Breakfast at Tiffany's,996,https://m.media-amazon.com/images/M/MV5BNGEwMT...,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,Giant,997,https://m.media-amazon.com/images/M/MV5BODk3Yj...,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
998,Lifeboat,999,https://m.media-amazon.com/images/M/MV5BZTBmMj...,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,The 39 Steps,1000,https://m.media-amazon.com/images/M/MV5BMTY5OD...,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [93]:
filas_sin_nulos = filas_nulas.dropna()
filas_sin_nulos

Empty DataFrame
Columns: [Series_Title, ID, Poster_Link, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Overview, Meta_score, Director, Star1, Star2, Star3, Star4, No_of_Votes, Gross]
Index: []

# **FILAS NULAS 'META_SCORE'**

In [94]:
filas_nulas_Meta = datos[datos['Meta_score'].isnull()]
filas_nulas_Meta

,Series_Title,ID,Poster_Link,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
20,Soorarai Pottru,21,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,2020,U,153 min,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
54,Ayla: The Daughter of War,55,https://m.media-amazon.com/images/M/MV5BNWJhMD...,2017,NaN,125 min,"Biography, Drama, History",8.4,"In 1950, amid-st the ravages of the Korean War...",NaN,Can Ulkay,Erdem Can,Çetin Tekindor,Ismail Hacioglu,Kyung-jin Lee,34112,NaN
55,Vikram Vedha,56,https://m.media-amazon.com/images/M/MV5BY2FiMT...,2017,UA,147 min,"Action, Crime, Drama",8.4,"Vikram, a no-nonsense police officer, accompan...",NaN,Gayatri,Pushkar,Madhavan,Vijay Sethupathi,Shraddha Srinath,28401,NaN
57,Dangal,58,https://m.media-amazon.com/images/M/MV5BMTQ4Mz...,2016,U,161 min,"Action, Biography, Drama",8.4,Former wrestler Mahavir Singh Phogat and his t...,NaN,Nitesh Tiwari,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Sanya Malhotra,156479,"12,391,761"
65,Taare Zameen Par,66,https://m.media-amazon.com/images/M/MV5BMDhjZW...,2007,U,165 min,"Drama, Family",8.4,An eight-year-old boy is thought to be a lazy ...,NaN,Aamir Khan,Amole Gupte,Darsheel Safary,Aamir Khan,Tisca Chopra,168895,"1,223,869"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,The Day the Earth Stood Still,873,https://m.media-amazon.com/images/M/MV5BMTU5NT...,1951,U,92 min,"Drama, Sci-Fi",7.7,An alien lands and tells the people of Earth t...,NaN,Robert Wise,Michael Rennie,Patricia Neal,Hugh Marlowe,Sam Jaffe,76315,NaN
874,Gilda,875,https://m.media-amazon.com/images/M/MV5BYWUxMz...,1946,Approved,110 min,"Drama, Film-Noir, Romance",7.7,A small-time gambler hired to work in a Buenos...,NaN,Charles Vidor,Rita Hayworth,Glenn Ford,George Macready,Joseph Calleia,27991,NaN
899,El cuerpo,900,https://m.media-amazon.com/images/M/MV5BNGMxZj...,2012,NaN,112 min,"Mystery, Thriller",7.6,A detective searches for the body of a femme f...,NaN,Oriol Paulo,Jose Coronado,Hugo Silva,Belén Rueda,Aura Garrido,57549,NaN
909,Celda 211,910,https://m.media-amazon.com/images/M/MV5BMjI2OD...,2009,NaN,113 min,"Action, Adventure, Crime",7.6,The story of two men on different sides of a p...,NaN,Daniel Monzón,Luis Tosar,Alberto Ammann,Antonio Resines,Manuel Morón,63882,NaN
913,Die Welle,914,https://m.media-amazon.com/images/M/MV5BMzc0Zm...,2008,NaN,107 min,"Drama, Thriller",7.6,A high school teacher's experiment to demonstr...,NaN,Dennis Gansel,Jürgen Vogel,Frederick Lau,Max Riemelt,Jennifer Ulrich,102742,NaN

# **FILAS NULAS DE 'CERTIFICATE'**

In [95]:
filas_nulas_certificate = datos[datos['Certificate'].isnull()]
filas_nulas_certificate

,Series_Title,ID,Poster_Link,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
30,Seppuku,31,https://m.media-amazon.com/images/M/MV5BYjBmYT...,1962,NaN,133 min,"Action, Drama, Mystery",8.6,When a ronin requesting seppuku at a feudal lo...,85.0,Masaki Kobayashi,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,42004,NaN
54,Ayla: The Daughter of War,55,https://m.media-amazon.com/images/M/MV5BNWJhMD...,2017,NaN,125 min,"Biography, Drama, History",8.4,"In 1950, amid-st the ravages of the Korean War...",NaN,Can Ulkay,Erdem Can,Çetin Tekindor,Ismail Hacioglu,Kyung-jin Lee,34112,NaN
77,Tengoku to jigoku,78,https://m.media-amazon.com/images/M/MV5BOTI4NT...,1963,NaN,143 min,"Crime, Drama, Mystery",8.4,An executive of a shoe company becomes a victi...,NaN,Akira Kurosawa,Toshirô Mifune,Yutaka Sada,Tatsuya Nakadai,Kyôko Kagawa,34357,NaN
92,Babam ve Oglum,93,https://m.media-amazon.com/images/M/MV5BNjAzMz...,2005,NaN,112 min,"Drama, Family",8.3,The family of a left-wing journalist is torn a...,NaN,Çagan Irmak,Çetin Tekindor,Fikret Kuskan,Hümeyra,Ege Tanman,78925,NaN
121,Ikiru,122,https://m.media-amazon.com/images/M/MV5BZmM0NG...,1952,NaN,143 min,Drama,8.3,A bureaucrat tries to find a meaning in his li...,NaN,Akira Kurosawa,Takashi Shimura,Nobuo Kaneko,Shin'ichi Himori,Haruo Tanaka,68463,"55,240"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,The Secret of Kells,921,https://m.media-amazon.com/images/M/MV5BMjEzMj...,2009,NaN,71 min,"Animation, Adventure, Family",7.6,A young boy in a remote medieval outpost under...,81.0,Tomm Moore,Nora Twomey,Evan McGuire,Brendan Gleeson,Mick Lally,31779,"686,383"
926,Dead Man's Shoes,927,https://m.media-amazon.com/images/M/MV5BMTI5Mz...,2004,NaN,90 min,"Crime, Drama, Thriller",7.6,A disaffected soldier returns to his hometown ...,52.0,Shane Meadows,Paddy Considine,Gary Stretch,Toby Kebbell,Stuart Wolfenden,49728,"6,013"
944,Batoru rowaiaru,945,https://m.media-amazon.com/images/M/MV5BMDc2MG...,2000,NaN,114 min,"Action, Adventure, Drama",7.6,"In the future, the Japanese government capture...",81.0,Kinji Fukasaku,Tatsuya Fujiwara,Aki Maeda,Tarô Yamamoto,Takeshi Kitano,169091,NaN
998,Lifeboat,999,https://m.media-amazon.com/images/M/MV5BZTBmMj...,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,The 39 Steps,1000,https://m.media-amazon.com/images/M/MV5BMTY5OD...,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [96]:
cant_filas_nulas_Meta = datos['Meta_score'].isnull().sum()
print(f"cantidad de filas nulas: {cant_filas_nulas_Meta}")

cantidad de filas nulas: 157

In [97]:
cant_filas_nulas_certificate = datos ['Certificate'].isnull().sum()
print(f"cantidad de filas nulas: {cant_filas_nulas_certificate}")

cantidad de filas nulas: 101

In [98]:
data_sin_nulos = datos.dropna(subset=['Certificate', 'Meta_score']) ## esto borra los nulos de cada columna
data_sin_nulos.info()  ### cuantos datos me quedaron

<class 'pandas.core.frame.DataFrame'>
Index: 787 entries, 0 to 997
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   787 non-null    object
 1   ID             787 non-null    int64
 2   Poster_Link    787 non-null    object
 3   Released_Year  787 non-null    object
 4   Certificate    787 non-null    object
 5   Runtime        787 non-null    object
 6   Genre          787 non-null    object
 7   IMDB_Rating    787 non-null    float64
 8   Overview       787 non-null    object
 9   Meta_score     787 non-null    float64
 10  Director       787 non-null    object
 11  Star1          787 non-null    object
 12  Star2          787 non-null    object
 13  Star3          787 non-null    object
 14  Star4          787 non-null    object
 15  No_of_Votes    787 non-null    int64
 16  Gross          714 non-null    object
dtypes: float64(2), int64(2), object(13)
memory usage: 110.7+ KB

In [99]:
promedio = data_sin_nulos.groupby('Director')['Meta_score'].mean()
promedio.head(10)

Director
Aaron Sorkin             77.000000
Abdellatif Kechiche      89.000000
Abhishek Kapoor          40.000000
Adam McKay               81.000000
Akira Kurosawa           92.666667
Alan J. Pakula           84.000000
Alan Parker              57.000000
Alejandro Amenábar       74.000000
Alejandro G. Iñárritu    79.000000
Alejandro Jodorowsky     76.000000
Name: Meta_score, dtype: float64

In [103]:
def filtro_war(genres):
  return 'War' in genres

# Se aplica el filtro utilizando apply
datosWar = data_sin_nulos[data_sin_nulos['Genre'].apply(filtro_war)]

In [104]:
nombresWar = datosWar[['Series_Title','IMDB_Rating','Meta_score']]
nombresWar.head(20) ## Head muestra los primeros 20 elementos

                     Series_Title  IMDB_Rating  Meta_score
24            Saving Private Ryan          8.6        91.0
46                 Hotaru no haka          8.5        94.0
50                     Casablanca          8.5       100.0
74                 Apocalypse Now          8.4        94.0
80                 Paths of Glory          8.4        90.0
84                           1917          8.3        78.0
90                      Incendies          8.3        80.0
93           Inglourious Basterds          8.3        69.0
104             Full Metal Jacket          8.3        76.0
150               Pan's Labyrinth          8.2        98.0
172                           Ran          8.2        96.0
182         Judgment at Nuremberg          8.2        60.0
192            To Be or Not to Be          8.2        86.0
236         Taegukgi hwinalrimyeo          8.1        64.0
268                       Platoon          8.1        92.0
278               The Deer Hunter          8.1        86.0
304  The Bridge on the River Kwai          8.1        87.0
408         Au revoir les enfants          8.0        88.0
412                     Kagemusha          8.0        84.0
430                Doctor Zhivago          8.0        69.0